/**
 * Supabase Client Initialization
 * This file is automatically generated by the Supabase CLI. It initializes the Supabase client
 * with your project's URL and public API key. This client instance is then used throughout the application
 * to interact with your Supabase backend services, including Edge Functions, database, and authentication.
 * 
 * IMPORTANT: Do not manually edit this file. Any changes to your Supabase project settings
 * should be updated via the Supabase CLI or dashboard, which will regenerate this file accordingly.
 */

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxvzrchcfzmaoftronkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94dnpyY2hjZnptYW9mdHJvbmttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNTA5OTAsImV4cCI6MjA2NDkyNjk5MH0.Yn4tOEWm4H5ZLNsEGAp_Q3JyP0RaaMoHnfRRX0R5vOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);